#!/usr/bin/env node
// Fetches live GitHub data for every grave and bakes it into
// src/data/baked.js, so the site never needs API calls at runtime.
//
// Usage:
//   export GITHUB_TOKEN=ghp_...   (recommended: 5000 req/h; without: 60 req/h)
//   node scripts/fetch-graves.mjs
//
// Validates every repo: 404s are reported at the end so bad entries can be
// pruned from the data files. Archived repos are frozen, so their "last
// words" never change — re-run whenever you feel like refreshing star counts.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import vm from 'node:vm';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const TOKEN = process.env.GITHUB_TOKEN || '';
const API = 'https://api.github.com';

function loadGraves(file, constName) {
  const code = readFileSync(join(root, 'src/data', file), 'utf8');
  const sandbox = {};
  vm.runInNewContext(code + `;__out = ${constName};`, sandbox);
  return sandbox.__out;
}

async function gh(path) {
  const headers = { Accept: 'application/vnd.github+json', 'User-Agent': 'dot-dead-baker' };
  if (TOKEN) headers.Authorization = `Bearer ${TOKEN}`;
  const res = await fetch(`${API}${path}`, { headers });
  if (res.status === 404) return { notFound: true };
  if (res.status === 403 || res.status === 429) {
    const reset = res.headers.get('x-ratelimit-reset');
    throw new Error(`Rate limited. ${TOKEN ? '' : 'Set GITHUB_TOKEN to raise the limit. '}Resets at ${reset ? new Date(reset * 1000).toLocaleTimeString() : '?'}`);
  }
  if (!res.ok) throw new Error(`${res.status} on ${path}`);
  return res.json();
}

const graves = [
  ...loadGraves('famousGraves.js', 'FAMOUS_GRAVES'),
  ...loadGraves('moreGraves.js', 'MORE_GRAVES'),
];
console.log(`Baking ${graves.length} graves${TOKEN ? ' (authenticated)' : ' (no token — slow limit!)'}…`);

const baked = {};
const missing = [];
const renamed = [];
let done = 0;

for (const g of graves) {
  done++;
  const tag = `[${done}/${graves.length}] ${g.repo}`;
  try {
    const repo = await gh(`/repos/${g.repo}`);
    if (repo.notFound) {
      missing.push(g.repo);
      console.log(`${tag} — 404 ✗`);
      continue;
    }
    if (repo.full_name && repo.full_name.toLowerCase() !== g.repo.toLowerCase()) {
      renamed.push(`${g.repo} → ${repo.full_name}`);
    }
    const entry = {
      stars: repo.stargazers_count,
      born: Number((repo.created_at || '').slice(0, 4)) || null,
      archived: !!repo.archived,
      lastCommitDate: (repo.pushed_at || '').slice(0, 10) || null,
    };
    const commits = await gh(`/repos/${g.repo}/commits?per_page=1`);
    if (Array.isArray(commits) && commits.length && commits[0].commit) {
      const c = commits[0];
      let msg = (c.commit.message || '').split('\n')[0].trim();
      if (msg.length > 100) msg = msg.slice(0, 97) + '…';
      entry.lastWords = {
        msg,
        who: (c.author && c.author.login) || (c.commit.author && c.commit.author.name) || 'unknown',
        date: ((c.commit.author && c.commit.author.date) || '').slice(0, 10),
      };
    } else {
      entry.lastWords = null;
    }
    baked[g.repo] = entry;
    console.log(`${tag} ★${entry.stars}${entry.archived ? ' [archived]' : ''} ✓`);
  } catch (e) {
    console.error(`${tag} — ${e.message}`);
    if (/Rate limited/.test(e.message)) process.exit(1);
  }
}

const out = `// Baked GitHub data, generated by scripts/fetch-graves.mjs — do not edit by
// hand. Generated ${new Date().toISOString().slice(0, 10)} for ${Object.keys(baked).length} repos.
const BAKED = ${JSON.stringify(baked, null, 1)};
`;
writeFileSync(join(root, 'src/data/baked.js'), out);
console.log(`\nWrote src/data/baked.js (${(out.length / 1024).toFixed(0)} KB, ${Object.keys(baked).length} repos).`);
if (renamed.length) {
  console.log(`\nRenamed repos (work fine via redirect, but consider updating):\n  ${renamed.join('\n  ')}`);
}
if (missing.length) {
  console.log(`\n404 — prune these from the data files:\n  ${missing.join('\n  ')}`);
}
